Update minificacion.yml

diff --git a/.github/workflows/minificacion.yml b/.github/workflows/minificacion.yml
--- a/.github/workflows/minificacion.yml
+++ b/.github/workflows/minificacion.yml
@@ -18,35 +18,40 @@ jobs:
 
       - name: Minify JavaScript
         run: | 
-          # Verifica si el archivo de configuración existe
-          if [ -f assets/javascriptFilesToMinify.json ]; then
-            # Lee el archivo de configuración
-            config=$(cat assets/javascriptFilesToMinify.json)
-            # Extrae la lista de archivos de entrada y salidas
-            filesToMinify=($(echo $config | jq -r '.javascriptFilesToMinify[] | .input'))
-            outputDirectories=($(echo $config | jq -r '.javascriptFilesToMinify[] | .output'))
+           # Verifica si el archivo de configuración existe
+            if [ -f assets/javascriptFilesToMinify.json ]; then
+              # Lee el archivo de configuración
+              config=$(cat assets/javascriptFilesToMinify.json)
+              # Extrae la lista de archivos de entrada y salidas
+              filesToMinify=($(echo $config | jq -r '.javascriptFilesToMinify[] | .input'))
+              outputDirectories=($(echo $config | jq -r '.javascriptFilesToMinify[] | .output'))
 
-            # Instala Terser
-            npm install terser -g
+              # Verifica si la lista de archivos a minificar está vacía
+              if [ ${#filesToMinify[@]} -eq 0 ]; then
+                echo "Error: La lista de archivos a minificar está vacía en assets/javascriptFilesToMinify.json."
+                exit 1
+              fi
+              # Instala Terser
+              npm install terser -g
 
-            # Realiza la minificación de JavaScript
-            for ((i=0; i<${#filesToMinify[@]}; i++)); do
-              file=assets/${filesToMinify[i]}
-              outputDirectory=${outputDirectories[i]}
+              # Realiza la minificación de JavaScript
+              for ((i=0; i<${#filesToMinify[@]}; i++)); do
+                file=assets/${filesToMinify[i]}
+                outputDirectory=${outputDirectories[i]}
 
-              # Obtiene el nombre del archivo de salida
-              filename=$(basename -- "$file")
-              extension="${filename##*.}"
-              filename="${filename%.*}"
+                # Obtiene el nombre del archivo de salida
+                filename=$(basename -- "$file")
+                extension="${filename##*.}"
+                filename="${filename%.*}"
 
               # Realiza la minificación
-              terser $file -o assets/$filename.min.$extension
+              terser $file -o assets/minified/$filename.min.$extension
             done
 
             # Añade y sube los archivos minificados
-            git add .
+            git add assets/minified
             git commit -m "Minify JavaScript"
             git push origin main
-          else
-            echo "Error: El archivo assets/javascriptFilesToMinify.json no existe."
-          fi
+            else
+              echo "Error: El archivo assets/javascriptFilesToMinify.json no existe."
+            fi
