Update minificacion.yml

diff --git a/.github/workflows/minificacion.yml b/.github/workflows/minificacion.yml
--- a/.github/workflows/minificacion.yml
+++ b/.github/workflows/minificacion.yml
@@ -22,27 +22,27 @@ jobs:
           cd assets
           # Verifica si el archivo de configuración existe
           if [ -f javascriptFilesToMinify.json ]; then
-            # Lee el archivo de configuración
-            filesToMinify=($(cat javascriptFilesToMinify.json))
-            # Verifica si la lista de archivos a minificar está vacía
-            if [ ${#filesToMinify[@]} -eq 0 ]; then
-              echo "Error: La lista de archivos a minificar está vacía en assets/javascriptFilesToMinify.json."
-              exit 1
-            fi
+          # Lee el archivo de configuración
+          filesToMinify=$(cat javascriptFilesToMinify.json)
 
-            # Instala Terser
-            npm install terser -g
+          # Verifica si la lista de archivos a minificar está vacía
+          if [ -z "$filesToMinify" ]; then
+            echo "Error: La lista de archivos a minificar está vacía en assets/javascriptFilesToMinify.json."
+            exit 1
+          fi
 
-            # Realiza la minificación de JavaScript
-            for file in "${filesToMinify[@]}"; do
-              # Obtiene el nombre del archivo de salida
-              filename=$(basename -- "$file")
-              extension="${filename##*.}"
-              filename="${filename%.*}"
+          # Instala Terser
+          npm install terser -g
 
-              # Realiza la minificación
-              terser $file -o $filename.min.$extension
-            done
+          # Realiza la minificación de JavaScript
+          for file in $filesToMinify; do
+            # Obtiene el nombre del archivo de salida
+            filename=$(basename -- "$file")
+            extension="${filename##*.}"
+            filename="${filename%.*}"
+            # Realiza la minificación
+            terser $file -o $filename.min.$extension
+          done
           else
             echo "Error: El archivo assets/javascriptFilesToMinify.json no existe."
           fi
