Update minificacion.yml

diff --git a/.github/workflows/minificacion.yml b/.github/workflows/minificacion.yml
--- a/.github/workflows/minificacion.yml
+++ b/.github/workflows/minificacion.yml
@@ -1,4 +1,5 @@
 name: Minificación
+
 on:
   push:
     branches:
@@ -12,14 +13,21 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
+      - name: Install jq
+        run: |
+          sudo apt-get update
+          sudo apt-get install jq -y
+
       - name: Minify JavaScript
         run: | 
           # Verifica si el archivo de configuración existe
           if [ -f assets/javascriptFilesToMinify.json ]; then
             # Lee el archivo de configuración
             config=$(cat assets/javascriptFilesToMinify.json)
-            # Extrae la lista de archivos de entrada
-            filesToMinify=($(echo $config | jq -r '.javascriptFilesToMinify[]'))
+
+            # Extrae la lista de archivos de entrada y nombres de salida
+            filesToMinify=($(echo $config | jq -r '.javascriptFilesToMinify[].input'))
+            outputNames=($(echo $config | jq -r '.javascriptFilesToMinify[].output'))
 
             # Verifica si la lista de archivos a minificar está vacía
             if [ ${#filesToMinify[@]} -eq 0 ]; then
@@ -27,21 +35,23 @@ jobs:
               exit 1
             fi
 
-            # Instala Terser
-            npm install terser -g
 
             # Cambia al directorio de assets para que Terser pueda encontrar los archivos
             cd assets
 
             # Realiza la minificación de JavaScript
-            for file in "${filesToMinify[@]}"; do
-              # Obtiene el nombre del archivo de salida
-              filename=$(basename -- "$file")
-              extension="${filename##*.}"
-              filename="${filename%.*}"
+            for i in "${!filesToMinify[@]}"; do
+              file="${filesToMinify[$i]}"
+              outputName="${outputNames[$i]}"
+
+              # Verifica si el archivo de entrada existe
+              if [ ! -f $file ]; then
+                echo "Error: El archivo $file no existe."
+                exit 1
+              fi
 
               # Realiza la minificación
-              terser $file -o $filename.min.$extension
+              terser $file -o $outputName
             done
 
             # Vuelve al directorio raíz del repositorio
